[package]
name = "rdma-sim"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]

[dependencies]
failure = "0.1.1"
itertools = "0.7.8"
slog = "2"
slog-bunyan = "2"
slog-term = "2"
viz = { path = "./sim-packet-viz" }
clap = "~2.32"
